import '@/app/globals.css'

export const metadata = {
  title: 'API Cars',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
